// frontend/src/components/ThemeToggle.vue
<template>
  <button class="theme-toggle icon-button" type="button" :aria-label="label" :title="label" @click="toggleTheme">
    <PhMoon v-if="theme === 'light'" :size="17" weight="regular" aria-hidden="true" />
    <PhSun v-else :size="17" weight="regular" aria-hidden="true" />
  </button>
</template>

<script setup lang="ts">
import { PhMoon, PhSun } from '@phosphor-icons/vue'
import { computed, onMounted, ref } from 'vue'

const theme = ref<'light' | 'dark'>('light')
const label = computed(() => (theme.value === 'light' ? '切换到深色主题' : '切换到浅色主题'))

function applyTheme(nextTheme: 'light' | 'dark') {
  theme.value = nextTheme
  document.documentElement.setAttribute('data-theme', nextTheme)
  localStorage.setItem('theme', nextTheme)
}

function toggleTheme() {
  applyTheme(theme.value === 'light' ? 'dark' : 'light')
}

onMounted(() => {
  const saved = localStorage.getItem('theme') as 'light' | 'dark' | null
  const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches
  applyTheme(saved || (prefersDark ? 'dark' : 'light'))
})
</script>

<style scoped>
.theme-toggle {
  flex: 0 0 auto;
}
</style>

// frontend/src/components/ThemeToggle.tsx
import { useState } from 'react'
import { Moon, Sun } from '@phosphor-icons/react'

const THEME_KEY = 'superagent.theme'
type Theme = 'light' | 'dark'

function resolveInitial(): Theme {
  const saved = localStorage.getItem(THEME_KEY)
  if (saved === 'dark' || saved === 'light') return saved
  return window.matchMedia?.('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'
}

/** Apply the persisted/system theme to <html>. Call once before render. */
export function initTheme() {
  document.documentElement.dataset.theme = resolveInitial()
}

export function ThemeToggle({ className }: { className?: string }) {
  const [theme, setTheme] = useState<Theme>(() => (document.documentElement.dataset.theme as Theme) || 'light')

  function toggle() {
    const next: Theme = theme === 'dark' ? 'light' : 'dark'
    document.documentElement.dataset.theme = next
    localStorage.setItem(THEME_KEY, next)
    setTheme(next)
  }

  return (
    <button type="button" className={className ?? 'icon-button'} onClick={toggle} aria-label="切换主题" title="切换主题">
      {theme === 'dark' ? <Sun size={18} aria-hidden="true" /> : <Moon size={18} aria-hidden="true" />}
    </button>
  )
}
