// frontend/src/features/chat/components/SessionRail.tsx
import { useNavigate } from 'react-router-dom'
import { Archive, PencilSimple, Plus, Trash } from '@phosphor-icons/react'
import { selectFilteredConversations, useChatStore } from '../store/chat'
import { formatChatTime } from '../utils/presentation'

export function SessionRail() {
  const navigate = useNavigate()
  const conversations = useChatStore(selectFilteredConversations)
  const selectedSessionId = useChatStore((s) => s.selectedSessionId)
  const keyword = useChatStore((s) => s.keyword)

  async function createConversation() {
    const id = await useChatStore.getState().createAndSelectConversation()
    if (id) navigate(`/chat/${id}`)
  }

  async function select(sessionId: number) {
    await useChatStore.getState().selectConversation(sessionId)
    navigate(`/chat/${sessionId}`)
  }

  async function rename(sessionId: number, current: string) {
    const next = window.prompt('重命名会话', current)
    if (next === null) return
    await useChatStore.getState().renameConversation(sessionId, next)
  }

  async function archive(sessionId: number) {
    await useChatStore.getState().archiveConversation(sessionId)
  }

  async function remove(sessionId: number) {
    if (!window.confirm('删除后无法恢复，确认继续吗？')) return
    await useChatStore.getState().removeConversation(sessionId)
  }

  return (
    <aside className="session-rail">
      <div className="session-rail__top">
        <h2>会话</h2>
        <button className="btn btn-primary btn-sm" type="button" data-testid="chat-new-conversation" onClick={createConversation}>
          <Plus size={15} aria-hidden="true" /> 新建
        </button>
      </div>

      <input
        className="input-control"
        placeholder="搜索会话…"
        value={keyword}
        onChange={(event) => useChatStore.getState().setKeyword(event.target.value)}
      />

      <div className="conversation-list">
        {conversations.length === 0 && <div className="empty-line">还没有会话，点击「新建」开始。</div>}
        {conversations.map((conversation) => (
          <div
            key={conversation.id}
            className={`conversation-row${conversation.id === selectedSessionId ? ' conversation-row--active' : ''}`}
          >
            <button className="conversation-row__main" type="button" onClick={() => select(conversation.id)}>
              <strong>{conversation.title || '未命名会话'}</strong>
              <small>{formatChatTime(conversation.lastMessageAt)}</small>
            </button>
            <div className="conversation-row__actions">
              <button className="btn-text btn-sm" type="button" onClick={() => rename(conversation.id, conversation.title)}>
                <PencilSimple size={13} aria-hidden="true" /> 改名
              </button>
              <button className="btn-text btn-sm" type="button" onClick={() => archive(conversation.id)}>
                <Archive size={13} aria-hidden="true" /> 归档
              </button>
              <button className="btn-text btn-sm danger-text" type="button" onClick={() => remove(conversation.id)}>
                <Trash size={13} aria-hidden="true" /> 删除
              </button>
            </div>
          </div>
        ))}
      </div>
    </aside>
  )
}

// frontend/src/features/chat/components/SessionRail.vue
<template>
  <aside class="session-rail" aria-label="会话列表">
    <div class="session-rail__top">
      <div>
        <p class="section-label">Sessions</p>
        <h2>会话</h2>
      </div>
      <button
        class="btn btn-primary btn-sm"
        data-testid="chat-new-conversation"
        :class="{ 'btn-loading': chatStore.creatingConversation }"
        :disabled="chatStore.creatingConversation"
        type="button"
        @click="$emit('create')"
      >
        <PhPlus :size="14" weight="bold" aria-hidden="true" />
        {{ chatStore.creatingConversation ? '创建中' : '新建' }}
      </button>
    </div>

    <label class="field session-search">
      <span>搜索会话</span>
      <input v-model="chatStore.keyword" type="search" placeholder="输入标题" />
    </label>

    <LoadingSpinner v-if="chatStore.loadingConversations" text="正在加载会话列表..." />
    <EmptyState v-else-if="chatStore.filteredConversations.length === 0" variant="chat" title="暂无会话" description="创建会话后开始提问。" />
    <nav v-else class="conversation-list" aria-label="会话列表">
      <article
        v-for="conversation in chatStore.filteredConversations"
        :key="conversation.id"
        class="conversation-row"
        :class="{ 'conversation-row--active': chatStore.selectedSessionId === conversation.id }"
      >
        <button type="button" class="conversation-row__main" @click="$emit('select', conversation.id)">
          <strong v-if="chatStore.editingConversationId !== conversation.id">{{ conversation.title }}</strong>
          <input
            v-else
            :value="conversation.title"
            class="conversation-row__rename"
            type="text"
            @click.stop
            @keyup.enter="$emit('rename', conversation.id, ($event.target as HTMLInputElement).value)"
            @blur="$emit('rename', conversation.id, ($event.target as HTMLInputElement).value)"
          />
          <small>{{ formatTime(conversation.lastMessageAt) }}</small>
        </button>
        <div class="conversation-row__actions">
          <button class="btn-text" type="button" @click="chatStore.editingConversationId = conversation.id">重命名</button>
          <button class="btn-text" type="button" @click="$emit('archive', conversation.id)">归档</button>
          <button class="btn-text danger-text" type="button" @click="$emit('remove', conversation.id)">删除</button>
        </div>
      </article>
    </nav>
  </aside>
</template>

<script setup lang="ts">
import { PhPlus } from '@phosphor-icons/vue'
import { EmptyState, LoadingSpinner } from '../../../components'
import { useChatStore } from '../store/chat'
import { formatChatTime } from '../utils/presentation'

defineEmits<{
  create: []
  select: [sessionId: number]
  rename: [sessionId: number, title: string]
  archive: [sessionId: number]
  remove: [sessionId: number]
}>()

const chatStore = useChatStore()
const formatTime = formatChatTime
</script>
